location                    = "uksouth"
product                     = "cvp"
wowza_sku                   = "linux-paid-4-9"
wowza_version               = "4.9.3"
dev_source_address_prefixes = "127.0.0.1"
