trigger:
  - none

pr:
  - none

schedules:
- cron: "0 7 * * Mon,Wed,Fri,Sun" 
  displayName: Weekly Pipeline Schedule
  branches:
    include:
    - master
  always: true

parameters:
- name: envs
  displayName: Wowza Environment
  type: object
  values: ['stg', 'prod', 'sbox']
  default: ['stg', 'prod']

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: VIH-10876-Add-fw-files
      endpoint: hmcts

jobs:
- ${{ each env in parameters.envs }}:
 - job: FW Enable
    displayName: 'Enable fw for ${{ env }}'
    variables:
      - template: .\pipeline\variables\variables-${{ lower(env) }}.yaml
    steps:
    - template: templates\Azure\KeyVault\firewall-enable.yaml@azTemplates
      parameters:
        subscription: ${{ parameters.subscriptionName }}
        keyVaultName: "cvp-${{ parameters.env }}-kv"
        resourceGroup: "cvp-sharedinfra-${{ parameters.env }}"

  - job: CertGen${{ env }}
    displayName: 'Generate Certificate for ${{ env }}'
    variables:
      - template: .\pipeline\variables\variables-${{ lower(env) }}.yaml
    steps:
      - template: templates\Azure\Certificates\Request-test.yaml@azTemplates
        parameters:
          subscriptionName: ${{variables.subscriptionName}}
          product: "cvp"
          environment: ${{lower(env)}}
          domain: "${{ variables.dns }}"
          keyVaultName: "cvp-${{lower(env)}}-kv"
          resourceGroupName: "cvp-sharedinfra-${{lower(env)}}"
  
   - job: FW Disable
    displayName: 'Disable fw for for ${{ env }}'
    variables:
      - template: .\pipeline\variables\variables-${{ lower(env) }}.yaml
    steps:
      - template: templates\Azure\KeyVault\firewall-disable.yaml@azTemplates
        parameters:
          subscription: ${{ parameters.subscriptionName }}
          keyVaultName: "cvp-${{ parameters.env }}-kv"
          resourceGroup: "cvp-sharedinfra-${{ parameters.env }}"
