location = "uksouth"
env      = "test"
product  = "cvp"
common_tags = {
  environment = "test"
  teamName    = "cvp"
  BuiltFrom   = "https://github.com/hmcts/cvp-audio-ingress"
}
dns_zone_name       = "shared-services.uk.south.test.hmcts.internal"
dns_resource_group  = "shared-services_test_network_resource_group"
dns_tenant_id       = "oops"
dns_client_id       = "dummy"
dns_client_secret   = "data"
dns_subscription_id = "a8140a9e-f1b0-481f-a4de-09e2ee23f7ab"
address_space       = "10.50.11.16/28"